name: Package and Release Python App with Briefcase

on: push

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase
          python -m pip install build

      - name: Build Package
        run: python -m build

      - name: Package the app with Briefcase
        run: briefcase package

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: packaged-app
          path: dist/  # Path to the packaged app folder (check Briefcase output folder)

  release:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-app
          path: dist/

      - name: Cache build files
        uses: actions/cache@v4
        with:
          path: dist/
          key: ${{ runner.os }}-${{ hashFiles('dist/**') }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          draft: false
          prerelease: false
          artifacts: "dist/*"  # Upload all files in the dist/ directory to the release